Voter registration form [IN PROGRESS]
8by8-org/8by8-challenge pull request #30
Opened 2024-09-03 07:25 UTC by dvorakjt

## Checklist
- [ ] Include the corresponding Jira issue key and #done in the PR title, like so: "JRA-123 #done Migrate Election Reminders"
- [x] Verify that the code compiles (npm run dev)
- [x] Verify that the project builds (npm run build)
- [ ] Verify that all tests pass
- [ ] Verify that unit tests cover 100% of the code
- [x] Create Storybook stories for visual components
- [x] Verify that any visual components match the Figma
- [x] Test with a screen reader (if applicable)
- [ ] Document your code with TSDoc comments
- [ ] Format your code with Prettier

## Overview
In this PR, I implemented the register to vote form. Some features of the form include:
- Real-time validation
- Directs user attention to the first non-valid field on a page when they try to submit an invalid form
- Redirects the user to the first incomplete page of the form
- Autocompleting US state fields based on zip
- Detecting the user's age based on their birthday and showing them state-specific pre-registration messages if they are under the voting age
- Address validation with Google maps API --- provides detailed validation methods and suggests fixes to spelling and other address components, improving user experience and preventing errors from making it to the voter registration paperwork
- Full support for screen readers via adherence to aria best-practices
- Form data persists in session storage unless the user logs out. Session storage is tab- and website-specific, keeping the user's information secure but improving UX should they refresh the page
- Ballot-qualified political parties are state specific and are loaded  through query params
- An animated progress bar

For a demo, please see [this video](https://www.awesomescreenshot.com/video/31120643?key=9fb25f4db1a9fd49fa5b9df3367fe953).

## Test Plan

> REQUIRED
> What you did to verify your PR works as claimed? Make sure to list **things/steps/screenshots/screentcasts** so that others can reproduce your test easily. Share styling changes and component updates through screenshots.

## Follow ups
- Ballot-qualified political parties need to be loaded from RTV's Rocky API
- A rate limiter should be applied to the validate-addresses endpoint
- The client-side method for registering to vote will need to call the appropriate API route

2024-09-15 05:13 UTC, ty730 requested changes
Awesome to see Fully Formed in action like this! Very impressive PR. Some small questions.

2024-09-15 05:13 UTC, ty730 commented on src/components/form-components/phone-input-group/index.tsx
Looks like you have an empty file, should this exist?

2024-09-15 05:13 UTC, ty730 commented on src/components/form-components/phone-input/phone-input.tsx
I'm seeing a lot of overlap between the code here and in src/components/form-components/input/input.tsx. Should this be an extension of the Input functional component? If there's a good reason not to that's then it's alright

2024-09-15 05:50 UTC, dvorakjt commented on src/components/form-components/phone-input-group/index.tsx
I forgot to export it, good catch!

2024-09-15 05:55 UTC, dvorakjt commented on src/components/form-components/phone-input/phone-input.tsx
The phone input auto-formats the phone number, so there is a significant difference in behavior, but I'll take a look to see if somehow extending the input component makes sense

2024-09-16 07:23 UTC, dvorakjt commented on src/components/form-components/phone-input-group/index.tsx
Fixed!

2024-09-16 07:31 UTC, dvorakjt commented on src/components/form-components/phone-input/phone-input.tsx
Looking at it further, I do think the different behavior warrants separate components.  

- The PhoneInput listens to the `beforeinput` event in order to capture the value entered by the user, format it and then display it, whereas the Input uses the more commonplace `onChange` event handler
- The PhoneInput requires the creation of a few additional refObjects
- The PhoneInput must manage cursor position to prevent it from jumping to the end of the value when the content is edited
- The PhoneInput must handle keyboard events differently as the cursor should skip over non-digit characters

One possibility that we could consider for the future would be to create reusable hooks for some of the common functionality, so that we are composing these components from shared functionality rather adding functionality to the Input that in most cases it won't use, but I think for now we can keep it simple and leave things as is.

2024-09-16 22:10 UTC, ty730 commented on src/components/form-components/phone-input/phone-input.tsx
Thanks for looking into it! Based on the differing requirements that PhoneInput needs I think it makes sense to keep them separate right now.

2024-09-16 22:10 UTC, ty730 approved these changes

2024-09-19 08:07 UTC, merged