CHAL-62 #done, CHAL-76 #done - Add actions page
8by8-org/8by8-challenge pull request #41
Opened 2024-09-30 04:56 UTC by dvorakjt

## Checklist
- [x] Include the corresponding Jira issue key and #done in the PR title, like so: "JRA-123 #done Migrate Election Reminders"
- [x] Verify that the code compiles (npm run dev)
- [x] Verify that the project builds (npm run build)
- [x] Verify that all tests pass
- [x] Verify that unit tests cover 100% of the code
- [x] Create Storybook stories for visual components
- [x] Verify that any visual components match the Figma
- [x] Test with a screen reader (if applicable)
- [x] Document your code with TSDoc comments
- [x] Format your code with Prettier

## Overview
This PR implements the /actions page and calls the takeTheChallenge() function from the "Take the challenge" button in the `<PlayerLinks />` component. Linting errors have been fixed and the `create-cryptokey` script imports the crypto module as there were issues with crypto being undefined without this import in some environments.

## Test Plan
Storybook stories have been created to visualize the various states of the /actions page, and the header stories have been updated to reflect the added functionality in the `<PlayerLinks />` component. Test coverage is 100% for all branches, statements, lines, and functions.

## Follow ups
N/A

2024-09-30 13:23 UTC, ty730 requested changes
One question

2024-09-30 13:23 UTC, ty730 commented on src/app/actions/hero/has-completed-all-actions/index.tsx
You have an empty file here. Is this supposed to be empty?

2024-09-30 14:30 UTC, dvorakjt commented on src/app/actions/hero/has-completed-all-actions/index.tsx
Fixed!

2024-10-01 01:34 UTC, ty730 approved these changes

2024-10-01 03:47 UTC, merged